### ISSUE TITLE
Build failure on Fedora 29

### ISSUE THREAD

**Issue by bowlofeggs** [pelzlpj/orpie#14]
I'm not familiar with ocaml, but I wanted to report that orpie [does not build on Fedora 29](https://bugzilla.redhat.com/show_bug.cgi?id=1605349) (due to release in October):

```
$ make
ocamlopt.opt -c -pp camlp4o -I ./curses -I ./gsl -I ./units -thread big_int_str.ml
File "big_int_str.ml", line 27, characters 5-12:
Error: Unbound module Big_int
make: *** [Makefile:285: big_int_str.cmx] Error 2
```

This is with ```ocaml-4.07.0-3.fc30.x86_64```.

**Comment by jared-wallace** [comment]
I was able to resolve this with two steps:

1) Explicit call to use "unsafe-string"
2) Requiring "ocaml-num-devel"

The first fix is required because ocaml switched the default from unsafe to safe, and the second was because the Num library was dropped from ocaml in favor of Zarith.

Both fixes are bandaids that do not address the underlying issues though.

**Comment by pelzlpj** [comment]
-unsafe-string is integrated into the build script with 1a2d225218213d850bdcd40ed87449c176690139. The ocaml-num-devel dependency will need to get resolved on Fedora's end (looks like it has already?).
